# Generated by Django 4.0.5 on 2022-06-25 04:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('taikorecord', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Difficulty',
        ),
        migrations.RenameField(
            model_name='music',
            old_name='music',
            new_name='title',
        ),
    ]
